### ISSUE TITLE
What is the "effect" and "p-adj" and "Significant" column in Fulco_interactions_wScore.txt

### ISSUE THREAD

**Issue by wangjk321** [SchulzLab/STARE#10]
Hi 

Thank you for your wonderful paper.

When I check you Zenodo directory (https://zenodo.org/records/7351632), I find three columns ("effect" and "p-adj" and "Significant") in the file `Fulco_interactions_wScore.txt`. How can we understand this kind of statistical results? is it from your STARE tools?

Thanks !

**Comment by DennisHeck** [comment]
Hey,

Thank you for your interest! 
These columns come from the Fulco et al. paper 2019 (https://doi.org/10.1038/s41588-019-0538-0), after intersecting them with our enhancer-gene interactions so that we could add the columns with the score of the different ABC-scoring versions. That means that it only has the entries for which we had a matching enhancer-gene interaction from the ABC-score. The same is true for the of Gasperini and Schraivogel.

Best wishes,
Dennis
