### ISSUE TITLE
TFBS enrichment without promoter region

### ISSUE THREAD

**Issue by Andi964** [SchulzLab/STARE#3]
Hello,

according to your publication:
Does Stare consider +-2500 bp around the TSS in its TFBS enrichment analysis?
If yes, (how) can this mode be deactivated to investigate only the enrichment in Enhancers?

Best
Andreas

**Comment by DennisHeck** [comment]
Hello!

STARE does not consider the whole ±2500bp around the TSS for the TF affinities, but enhancer peaks that overlap with this ±2500bp window. Those peaks overlapping the promoter window are always considered, independent on whether they were linked to that gene in a preceding ABC-scoring step or not. We don't have an option to turn that off, as we found those peaks to be especially informative, and because the contact frequency in the ABC-score in that case is the contact of the region with itself. A workaround would be to remove any peaks from the candidate enhancer file that overlaps a promoter window, but then again that could remove potential enhancers of other genes. 

Best wishes,
Dennis

**Comment by Andi964** [comment]
Many thanks for your quick answer!
But in this case...I assume that your method would map the enhancers to those TSS since they are sooooo close?

Best Andreas
