### ISSUE TITLE
Different number of enhancers for abc and adapted model

### ISSUE THREAD

**Issue by Andi964** [SchulzLab/STARE#6]
Hello,

the number of enhancer-target pairs (no-threshold) between ABC and your adapted model (considering just one tss) differs (ABC is more). What is the reason for that since both methods use the same HI-C input and peak regions?

Best Andreas

**Comment by DennisHeck** [comment]
Hey Andreas,

The reason should be that we skip interactions where the activity of an enhancer is 0. Now with the adapted activity there can be cases, where the enhancer activity was >0, but the contact to the gene is 0 (given pseudocount is turned off). Then the adapted activity will be 0 as well and these interactions will be skipped. Since the regular ABC doesn't scale the enhancer activity with the relative contact, it should still write them in that mode. 
The reasoning was that it's an easy catch for enhancers that are likely not relevant, saves time and memory, but I was already considering to change that behaviour in a future release, because of the mismatch between modes you describe.

Best wishes,
Dennis
